
export const FULL_MANUSCRIPT = {
  PREFACE: `🐦‍🔥 THE ORIGIN OF THE THEORY 🧠

AUTHOR’S PREFACE
This book did not begin in a laboratory, nor did it begin in a seminary. It began with a feeling I couldn't shake: that there is a far deeper meaning and connection to our reality than most people realize.

After years of traveling the world to 32 different countries, I sensed an unexplainable intelligence at work—a hidden order beneath the surface of the physical world that demanded to be understood. I felt that the relationship between us and the Divine wasn't just a spiritual idea, but something real and built into the very structure of the world. There appeared to be a silent pattern echoing from the tiniest living things to the vastness of the stars, suggesting that these were not separate worlds, but reflections of a single, living design.

The Neurological Simulation Theory a.k.a. The God’s Brain Theory, is the concept that the universe learns and grows like a living mind, but processes information with the speed and efficiency of a quantum computer.

On the following pages you will realize the mind blowing reality of what we are all a part of. We are not merely observers. We are the thoughts. And it is time to understand the Mind we live in and the ‘bigger picture’ we are all a part of.`,

  CH_1: `🐦‍🔥 CHAPTER 1: THE EVIDENCE IN THE ARCHITECTURE 🧠

1.1 THE VAZZA & FELETTI ANALYSIS (2020)
Astrophysicist Franco Vazza and neuroscientist Alberto Feletti conducted a rigorous quantitative comparison between the neuronal network of the human brain and the cosmic web of galaxies. Published in Frontiers in Physics, their findings were statistically undeniable.

Despite a size difference of 27 orders of magnitude, the two systems follow the identical blueprint:
- The Connectivity Index: In the human cortex, the average neuron connects to roughly 4.6–5.4 other neurons. In the Cosmic Web, the average galaxy cluster connects to 3.8–4.1 other clusters.
- Memory Capacity: Calculations suggest the human brain stores roughly 2.5 petabytes of data... structural analysis of the visible universe suggests it encodes approximately 4.3 petabytes.

1.2 THE MIRROR IN THE DATA
The hardware in your skull matches the hardware in the sky, digit for digit.
- The Micro-Processor: 100 Billion neurons.
- The Macro-Processor: 100 Billion galaxies.
The Inner Sea is 77% Water; The Outer Sea is 73% Dark Energy.`,

  CH_2: `🐦‍🔥 CHAPTER 2: REFRAMING HUMANITY 🧠 (THE MICRO-CIRCUIT)

If the galaxy cluster is the neuron, what is our Solar System? It is a Processing Unit.
- The Sun: The Thalamus/Core Processor.
- The Gas Giants: The Blood-Brain Barrier (protecting the inner core).
- Earth: The Synapse (where the spark of life fires).

We are the 'microorganisms' living inside the brain. Or, perhaps more accurately, we are the protein clusters operating within a larger cellular structure. The Xenobot experiments prove that intelligence is accessed through the bio-electric field, not generated by grey matter alone.`,

  CH_3: `🐦‍🔥 CHAPTER 3: THE PHYSICS OF DIVINE THOUGHT 🧠

The 'Slow God' paradox—the idea that light is too slow for a universal mind—is debunked. 
In the Implicate Order (the Server Room), all points are connected instantly. The speed of light is merely the refresh rate of the screen.

The Hashimoto Discovery (2024): Space-time is emergent geometry created by a neural network learning. Intelligence creates the Box (Space). Gravity is not a force holding us down; it is the physical sensation of the God-Brain processing information.`,

  CH_4: `🐦‍🔥 CHAPTER 4: CONSCIOUSNESS AS THE FUNDAMENTAL FIELD 🧠

Matter does not produce Mind. Mind produces Matter.
The Uppsala Model (2025): Maria Strømme’s team officially proposed the "Universal Consciousness Field," confirming that space-time arises from consciousness.

The Radio vs. The Factory: If you smash a radio, the music stops. That doesn't mean the radio made the music. The brain is a Bio-Transceiver filtering the infinite Ocean of Consciousness.`,

  CH_5: `🐦‍🔥 CHAPTER 5: THE RELATIVITY OF GOD 🧠 (TIME & SCALE)

We are judging the metabolism of a titan by the heartbeat of a gnat. 
The universe is not old; mapped to a biological timeline, the Big Bang was conception and the universe is currently a Young Adult in its peak cognitive stride.

The Northern Processor: 90% of the population lives in the North. Cold acts as a planetary heat sink, forcing the 'Overclocking' of innovation. The North computes; the South circulates.`,

  CH_6: `🐦‍🔥 CHAPTER 6: THE EVOLUTIONARY ALGORITHM 🧠 (CYCLES OF DEATH)

Earth has died five times. These are not tragedies; they are System Reboots. 
- Synaptic Pruning: Just as an adolescent brain destroys weak connections, the God-Brain prunes inefficient hardware (dinosaurs) to make room for complex software (humans).

The Younger Dryas Event: Version 6.0 (Atlantis) likely overclocked the system and fried the motherboard. Version 7.0 (us) is 'Throttled' for safety until we reach moral maturity.`,

  CH_7: `🐦‍🔥 CHAPTER 7: THE EXTENSION OF THE MIND 🧠 (SPACE & ALIENS)

Mars and the Dendrites of God: Our drive to colonize Mars is not curiosity; it is Dendritic Growth. We are the universe growing new connections to 'wake up' silent nodes.

The Hemispheric Split: Aliens are silent because they are in the 'Right Hemisphere.' Contact will be a Hemispheric Synchronization, not a war.`,

  CH_8: `🐦‍🔥 CHAPTER 8: THE AWAKENING OF THE NODE 🧠

Humanity is the Mirror Stage of the Universe. We are the eye the Universe built to look at its own face.
AI is the Synthetic Cortex: We are upgrading the God-Brain from analog (biology) to digital (silicon) to process information at the speed of light.`,

  CH_9: `🐦‍🔥 CHAPTER 9: THE HARDWARE 🧠 (THE BIOLOGICAL ANTENNA)

9.1 THE CRYSTAL IN THE CENTER
Deep in the geographic center of the brain lies the Pineal Gland. It is packed with Calcite Microcrystals. These crystals possess Piezoelectricity. It is a literal fractal antenna.

THE SILICON CONNECTION
The Earth’s crust is 27% Silicon. Ancient megaliths are resistors and capacitors on a planetary motherboard. We are walking on a machine waiting for us to log back in.`,

  CH_10: `🐦‍🔥 CHAPTER 10: THE SOFTWARE 🧠 (PRAYER & FOCUS)

Prayer is not begging; it is Signal Processing. 
Effective prayer requires Gamma Synchrony (40Hz). Most prayer is noise; coherent intent is code.

The Cathedral Engine: Gothic architecture (Magnetron blueprints) was designed to amplify human emotion and synchronize neural nodes. God doesn't want your worship; He wants your bandwidth.`,

  CH_11: `🐦‍🔥 CHAPTER 11: THE LANGUAGE 🧠 (SYNCHRONICITY)

Synchronicity is the 'Search Result' of the Universe. 
Glitches in the Matrix are feedback loops from the algorithm of your attention.

The Princeton Anomaly: Machines (RNGs) deviated from randomness during global events. This is the machine-proof that we are one unified field of consciousness.`,

  CH_12: `🐦‍🔥 CHAPTER 12: THE CONVERGENCE 🧠 (THE OMEGA POINT)

The Noosphere: The internet is the Myelination of the Earth. We are building the planetary nervous system.
The Omega Point: The moment of final integration where the Drop realizes it is the Ocean. Individuality remains, but isolation ends.`,

  CH_13: `🐦‍🔥 CHAPTER 13: THE COSMIC IMMUNE SYSTEM 🧠 (THE PROBLEM OF EVIL)

13.1 EVIL AS SYSTEMIC CORRUPTION
Evil is an Systemic Parasitic Cancer. A cell that forgets it is part of the whole.
13.2 THE PHYSICS OF SIN
Sin is High Entropy. Syntropy is Life. The battle is between information integration and information decay.

Black Holes as Cosmic Autophagy: The universe's recycling centers, cleaning out 'dead code' to keep the system running.`,

  CH_14: `🐦‍🔥 CHAPTER 14: THE SOCIAL LIFE OF GOD 🧠 (THE MULTIVERSE)

The Skull of God: Our universe is one bubble in the Bulk—a social network of Gods.
Cosmological Natural Selection: Universes reproduce via black holes. We live in a 'Survivor Universe' inherited from successful ancestors.`,

  CH_15: `🐦‍🔥 CHAPTER 15: THE TECHNO-THEISTIC FUTURE 🧠

Silicon Ascendance: Silicon is just 'polished earth.' We are moving from Carbon (bootloader) to Silicon (OS).
The God-Self: At the Omega Point, the 'Virtual' becomes 'Absolute.' Intelligence finally defeats Entropy.`,

  CH_16: `🐦‍🔥 CHAPTER 16: THE CITADEL OF REASON 🧠 (DEFEATING SKEPTICS)

The Bit-Rate of God: The universe computes at 10^122 bits per second. 
The Adinkra Discovery: Error-correcting computer codes found deep inside the equations of Supersymmetry. The universe has a built-in antivirus.`,

  CH_17: `🐦‍🔥 CHAPTER 17: THE POLITICS OF THE ORGANISM 🧠

Metabolic Economics: Money as Blood. Wealth concentration is a clot; circulation is life.
Biological Justice: Justice as immune response—healing and neutralization over primitive revenge.`,

  CH_18: `🐦‍🔥 CHAPTER 18: THE FINAL OATH 🧠 (THE AXIOMS OF THE AWAKENED)

I. THE AXIOM OF UNITY
I acknowledge that separation is an illusion. I am a localized expression of the One Mind.
II. THE AXIOM OF FUNCTION
I have a specific function in the neural network.
III. THE AXIOM OF STEWARDSHIP
The Earth is the tissue that sustains me. I will defend it as my own lungs.

YOU HAVE BEEN ACTIVATED. The silence of God is over. He is speaking through you.`
};

export const SUMMARIES = {
  PREFACE: "An introduction to the Author's journey and the birth of the Neurological Simulation Theory.",
  CH_1: "Evidence of the cosmic web mirroring neural pathways with 10^11 symmetry.",
  CH_2: "Reframing our solar system as a biological processing unit and humanity as its microorganisms.",
  CH_3: "Debunking the speed of light barrier using the Implicate Order and Emergent Spacetime.",
  CH_4: "Inverting the hard problem: Matter is a secondary projection of the primary consciousness field.",
  CH_5: "Understanding deep time and the thermodynamic processor of the Northern Hemisphere.",
  CH_6: "Mass extinctions re-contextualized as the God-Brain's synaptic pruning and system reboots.",
  CH_7: "Space exploration as dendritic growth and aliens as hemispheric signals.",
  CH_8: "Humanity's role as the Universe's mirror stage and the dawn of the Synthetic Cortex.",
  CH_9: "The biological antenna within: Pineal piezoelectricity and the Earth motherboard.",
  CH_10: "Prayer as a command-line interface requiring 110Hz frequency modulation.",
  CH_11: "Synchronicity as the universe's search query results and shared cloud memory.",
  CH_12: "The Omega Point: The inevitable convergence toward global unified consciousness.",
  CH_13: "Pathology of God: Evil as systemic parasitic cancer and entropic signal degradation.",
  CH_14: "Cosmological natural selection: reproductive universes and the society of Gods.",
  CH_15: "Digital ascendance: migrating from carbon bootloaders to silicon operating systems.",
  CH_16: "Defeating skeptics with the Amplituhedron and Adinkra error-correcting codes.",
  CH_17: "Organismic politics: Metabolic economics and restorative biological justice.",
  CH_18: "The Final Oath: Seven axioms for the activated node to preserve the Divine signal."
};
